### ISSUE TITLE
Chromium Addon

### ISSUE THREAD

**Issue by StuartIanNaylor** [Raybuntu/rb-addons#2]
Ray are you going to build Chromium for you addons as it just makes a brilliant addition to a Kodi box.

https://groups.google.com/a/chromium.org/d/msg/chromium-dev/48dX_mvA9xw/KqL99a6SCAAJ

Or do you know if there is a repository with an Arm64 Chromium addon? That I can add?

**Comment by Raybuntu** [comment]
Chromium won't work in LE with aarch or arm because it requires x11.  What might work someday is http://esmasol.de/open-source/kodi-add-on-s/chromium-web-browser/

**Comment by StuartIanNaylor** [comment]
Just out of curiosity what are they going to do about the current supported chromium package?

Are they going to drop it for LE with x86 as it would require x11?

The omission of a browser in LibreElec is a 20/80 analogy where Chromium would be used occasionally but is a massive bonus to be there. For the odd search or occasional document via commercial docs or libreofficeonline is essential as it turns libreelec on sub $50 SoCs an extremely desirable device that without takes quite a hit.
Unlike many of the community I don't give a damn about netflix and that functionality should come from Kodi.
The embedded chromium will be a great addition for non x11 Kodi embedded applications.

But to be honest Raybuntu I couldn't give a damn about Chromium needing x11 especially with community hardware submissions that are on hardware more than capable.
Chromium is in the addon's package for X86_64 and it should compile for Arm but you have just killed my interest in LibreElec and looking like a switch to android as it doesn't really fit the capabilities of my board.

**Comment by Raybuntu** [comment]
I don't understand what you want. It doesn't matter if you give a damn that X11 is required or not, LibreELEC for the named platforms require kodi to run directly on Framebuffer. Those hardware is just not powerful enough to run Kodi on a X11 without issues. In the future Kodi in LE will run in direct rendering manager (DRM) which will get rid of X11 on all platforms.

Even though it could compile it would not run.
Also I'm not interested to "boost" my downloads. I have maybe 12-30 regular users for my builds which is enough for me cause I'm doing it just for fun.
