### ISSUE TITLE
Updated version of Inputstream.adaptive

### ISSUE THREAD

**Issue by pszafer** [Raybuntu/rb-addons#3]
Hello,
I'm using your build of LibreELEC for Odroid C2.
In that I have inputstream.adaptive installed 2.1.4 and from yesterday netflix stopped working
https://github.com/asciidisco/plugin.video.netflix/issues/246

I'd like to check if this still occurs with inputstream 2.1.8 but I cannot find any newer version for arm (newer than 2.1.4.6).

Thanks for help!

**Comment by Raybuntu** [comment]
It's in my repo: http://raybuntu.libreelec.tv/addons/9.0.4/Odroid_C2/arm/inputstream.adaptive/
it's no longer hosted here. I just keep the repo up here for older builds.

**Comment by pszafer** [comment]
Got it, thanks for help.
So as I understand this repofile is no longer correct - https://github.com/Raybuntu/rb-addons/releases
Is there new repo file which I should install?

**Comment by Raybuntu** [comment]
There is no need for a repo zip. This one is pretty old and only for 8.1. All my builds have my repo preinstalled.
